/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/3DObjects/headphones/headphones.gltf -r public
Author: D31T7 (https://sketchfab.com/D31T7)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-headphone-960ac9ae4baa45b586fc5037a6e3bc96
Title: Simple Headphone
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useThree } from '@react-three/fiber'

export function Headphones(props) {
  const { nodes, materials } = useGLTF('/3DObjects/headphones/headphones.gltf')
  const { viewport } = useThree()
  return (
    // <group {...props} dispose={null} scale={(viewport.width / 30) *1.25} position={[0, .5, -2]} rotation={[0, 0, 0]}>
    <group {...props} dispose={null} scale={.25} position={[0, .5, -2]} rotation={[0, 0, 0]}>
      <mesh geometry={nodes.HeadbandConnector_MSH_lambert1_0.geometry} material={materials.lambert1}>
      <meshPhysicalMaterial 
            color="#c9b118"  
            roughness={0}
            emissive={'#000'}
            clearcoat={1}
            reflectivity={0.2}
            metalness={1}
            iridescence={0.1}
            iridescenceIOR={1}
            iridescenceThicknessRange={[100,1000]}         
          />
      </mesh>
      <mesh geometry={nodes.HeadBand_MSH_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.PhoneHangerRight_MSH_lambert1_0.geometry} material={materials.lambert1}/>
      <mesh geometry={nodes.Phoneright_MSH_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.Earcupright_MSH_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.PhoneHangerLeft_MSH_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.PhoneLeft_MSH_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.EarcupLeft_MSH_lambert1_0.geometry} material={materials.lambert1} />
    </group>
  )
}

useGLTF.preload('/3DObjects/headphones/headphones.gltf')
