/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/3DObjects/phone/phone.gltf -r public
Author: kaikye (https://sketchfab.com/kaikye)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/basic-smartphone-a6ef6ff8c6d141f6ab17040f72f192ea
Title: Basic Smartphone
*/

import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'



export function Phone(props) {
  const { viewport } = useThree()
  const { nodes, materials } = useGLTF('/3DObjects/phone/phone.gltf')
  
  const phone = useRef()
  const scroll = useScroll()
  const tl = useRef()
  
  useFrame((state, delta)=>{
    tl.current.seek(scroll.offset * tl.current.duration())
  })
  
  useLayoutEffect(() => {
    const ctx = gsap.context(() => {
      tl.current = gsap.timeline({defaults: {duration: 2, ease: 'power1.inOut'}})
      // tl.current = gsap.timeline({defaults: {duration: 2}})

      
      tl.current
      .to(phone.current.position, {x:0, y:0, z:9.8}, 2)
      .to(phone.current.rotation, {x:0, y:-2*Math.PI, z:-Math.PI/2}, 2)
      
      .to(phone.current.position, {x:0, y:.15, z:9.8}, 40)
      
      }, phone)
      return ()  => ctx.revert()
    }, [])


  return (
    <group {...props} dispose={null} ref={phone} scale={.3} position={[2.75, 1, -1]} rotation={[0, -1.25, -1.75]} >
      <group >
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Material.018']} material-color="white">
          <meshPhysicalMaterial 
                color="black"  
                roughness={0}
                emissive={'#000'}
                clearcoat={1}
                reflectivity={0.2}
                metalness={1}
                iridescence={0.1}
                iridescenceIOR={1}
                iridescenceThicknessRange={[100,1000]}         
              />
        </mesh>
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.019']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.020']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.021']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Material.022']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.023']} />
      </group>
    </group>
  )
}

useGLTF.preload('/3DObjects/phone/phone.gltf')
