/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/3DObjects/soccer/soccerBall.gltf -r public
Author: typhomnt (https://sketchfab.com/typhomnt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/soccer-ball-46c91864ef384158b0078e20bdbfe3e9
Title: Soccer Ball
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useThree } from '@react-three/fiber'

export function SoccerBall(props) {
  const { nodes, materials } = useGLTF('/3DObjects/soccer/soccerBall.gltf')
  const { viewport } = useThree()

  return (
    <group {...props} dispose={null} scale={1} position={[-3, 1, -1 ]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Black_s} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.White_s} >
          <meshPhysicalMaterial 
              color="#c9b118"  
              roughness={0}
              emissive={'#000'}
              clearcoat={1}
              reflectivity={0.2}
              metalness={1}
              iridescence={0.1}
              iridescenceIOR={1}
              iridescenceThicknessRange={[100,1000]}         
            />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/3DObjects/soccer/soccerBall.gltf')
